### ISSUE TITLE
Test the Collecting module

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Collecting#18]
Download and install the module. Collecting forms are site-specific, so you'll have to add a site if you haven't already. You should see a "Collecting" link at the bottom of the site's menu. Click on it and add a new form. Use this form to create a collecting form—something like "Share your photo" or "Share your story." Explore the interface a bit and use your imagination. It should be flexible enough to accommodate most forms.

Once you're done you'll need to add the collecting form to a site page. Edit any page and you should see a "Collecting" block. Click it, select your form, and save the page. You can now see your form by clicking "View." Go ahead and fill out your form and submit it.

Go back to the admin collecting interface, click on your form's label and then "Collected Items". You should see the item that you just submitted in a review interface. Explore the interface a bit.

That's the module in a nutshell. There's a few details I left out that you should notice as you're exploring the interfaces.

@mebrett

**Comment by mebrett** [comment]
Comments and questions based on initial round of testing:
Deleting form does not delete items submitted through that form (is this expected behavior)?

It feels like there are a lot of clicks to get to a collected item to review and approve it - partly because I tend to click through to the submitted item (rather than expanding the details drawer) and then have to click back to the table in order to approve an item. I'm thinking about workflow for community collecting projects and what suggestions to make in the documentation.

Are we planning to build in some sort of notification or indicator for submitted items?

**Comment by sheilabrennan** [comment]
@jimsafley if I wanted to include a terms of service that was required for review in order to submit, would I create another page, and then link to that page through an HMTL block of text in the form and require it?

**Comment by jimsafley** [comment]
There's a "Collecting terms of service" site setting that, once filled out, automatically enables a ToS checkbox on every form in that site.

reCAPTCHA protection acts similarly: complete the site and secret key in the site settings and the widget automatically appears on every form in that site.

**Comment by sheilabrennan** [comment]
Ok, cool. @mebrett and I will take a look at it next week.
