### ISSUE TITLE
Add resource selection to form

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-modules/Collecting#31]
Would be nice to be able to restrict an item property in a collecting form to the item pool for the site or to a particular item set. It would sort of make it like a controlled vocabulary for the form.

**Comment by jimsafley** [comment]
This is a WIP in the [item-input-type](https://github.com/omeka-s-modules/Collecting/compare/item-input-type) branch. Do not test on production installations because it requires an upgrade that cannot easily be downgraded.

This adds an "Item Resource" input type for "Property" prompts. The form builder can filter the items that are available to users by entering an advanced search query string (e.g. filter by template, class, site, etc.). When completing a public form, the user will see a select menu containing all items satisfying the filter, in the format: `#{ID}: {Title}`. The selected item will be saved as a resource value.
