### ISSUE TITLE
Testing: reviewers and editors should see private collected data

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Collecting#63]
The [role-has-permission](https://github.com/omeka-s-modules/Collecting/tree/role-has-permission) branch corrects an oversight that did not let reviewers and editors see private collected data. Omeka Reviewer and Editor users should see all "User Private," "User Name," and "User Email" text, regardless of anonymity type, or if the user submits anonymously.

**Comment by mebrett** [comment]
Tested and confirmed that it works as expected.

**Comment by GitByrd** [comment]
Thank you for for fixing this aspect in 1.5.1! 

I thought it was possible before, but I'm wondering if a reviewer or even an editor should be able to change the status select box from "needs review" to "public" or "private". I think as reviewers go through to review these items, the status should change, otherwise if there's more than one reviewer, they will become confused on whether the items still need review or not. 

Also, no big deal as you can still access the area, but I noticed that the little "review collected items" icon is no longer there when you initially click into the Collecting section in the admin.

**Comment by jimsafley** [comment]
It was not possible before, but it makes sense that it should be possible. I'll look into it.

**Comment by jimsafley** [comment]
@GitByrd A reviewer or editor can change the status if they are assigned to the site as an "editor" under the site's "User permissions". One downside to this is your "editors" will be able to update and delete site pages. This is less than desirable, but we have to balance contributor confidentiality with ease of workflow.

**Comment by GitByrd** [comment]
Ah ok, thanks! Well, that's at least better than having to grant site administrator privileges! Thanks for pointing that out.
