### ISSUE TITLE
Module entry in sidebar appears despite user roles

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/Collecting#79]
My audit of module behaviour shows this one appears in the sidebar even when a user role / site user role should not display it. 
In this test, a Researcher role who has no permissions on the displayed site is able to see this:

![showingup](https://user-images.githubusercontent.com/28012148/181099491-f0f9ea9a-94dd-43c8-a592-b491ad1c2510.PNG)

You get the 
"Collecting Forms
"This site has no collecting forms."

page with no buttons. Not sure what the intended behaviour is - perhaps people who are not assigned to a site should still be able to, I dunno, do some moderation on this page? So if this is working as intended, feel free to close this. Thanks!

**Comment by jimsafley** [comment]
An interesting question. Perhaps researchers should only have access to read collecting forms if they have site viewer permission. Right now access is determined by whether the site is public. I think for now I'm going to close this since no one has complained that the permissions are too lenient, .
